name: Auto Tap Cron Job

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  auto-tap-process:
    runs-on: ubuntu-latest
    
    steps:
    - name: Call Supabase Auto Tap Cron
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json" \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          "https://dbzixkwftyojksguisfb.supabase.co/functions/v1/auto-tap-cron-public" \
          --fail \
          --show-error \
          --max-time 30 \
          || echo "Auto tap cron failed or no active sessions"
    
    - name: Log completion
      run: echo "Auto tap cron job completed at $(date)"